module.exports={
  configurewebpack:{
    resolve:{
      alias:{
        'assets':'@/assets',
        'component':'@/component',
        'network':'@/network',
        'views':'@/views'
      }
    }
  }
}
